version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
    ports:
      - "9092:9092"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: retry_db
    ports:
      - "5432:5432"

  microservice-1:
    build:
      context: ./microservice-1
    container_name: microservice-1
    depends_on:
      - kafka
      - postgres
    environment:
      QUEUE_BROKER: kafka:9092
      QUEUE_TOPIC: my-topic
      QUEUE_GROUP_ID: my-group
      RETRY_TARGET_URL: http://microservice-2:8081/api/data
      RETRY_DELAY: 10s
      DATABASE_URL: postgres://user:password@postgres:5432/retry_db?sslmode=disable
    ports:
      - "8080:8080"

  microservice-2:
    build:
      context: ./microservice-2
    container_name: microservice-2
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/retry_db?sslmode=disable
    ports:
      - "8081:8081"
networks:
  default:
    driver: bridge